### ISSUE TITLE
passing parameters to 'get'

### ISSUE THREAD

**Issue by maxlath** [jpstevens/qreq#4]
hi,
using qreq.get, I build a request as such:

```
qreq.get('https://www.example.com/endpoint?action=search&language=en&search=whatever')
```

but for clarity, I woud like to do this by passing an object as such

```
qreq.get('https://www.example.com/endpoint', {action: 'search', language 'en', search: 'whatever'})
```

Is there a way to adapt ArgParser to match this case or would that be out of the method purpose?

Thanks for this handy utility!

**Comment by jpstevens** [comment]
Nice :+1:
The library is based on [mikeal/request](https://github.com/mikeal/request), which has a `qs` option. Have you tried adding a `qs` option to your get request?

``` javascript
qreq.get('https://www.example.com/endpoint', {
  qs: {
    action: 'search',
    language 'en',
   search: 'whatever'
  }
});
```

PS. I've not tried it yet...
